name: yolo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.7
  - pip:
    - torch==2.0.1
    - torchvision==0.15.2
    - opencv-python
    - pillow==10.2.0
    - ultralytics==8.1.15
    - ipykernel
    - tqdm

